version: '3'

networks:
  app_net:
    external:
      name: app_net

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306" 
    networks:
      - app_net
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql
    depends_on: 
      - mysql
    ports:
      - 8183:80
    environment:
      PMA_HOST: "docker.for.mac.localhost"
      PMA_PORT: "3306"
      PMA_USER: root
      PMA_PASSWORD: admin
      PMA_ARBITRARY: 1
    networks:
      - app_net